export const actionTypes = {

  //LOGIN
  VERIFICAR_INGRESO_LOGIN: "VERIFICAR_INGRESO_LOGIN",
  RESULT_VERIFICAR_LOGIN: "RESULT_VERIFICAR_LOGIN",
  SET_LOGIN: "SET_LOGIN",
  
  //
  GET_LISTA_ACCIONES:"GET_LISTA_ACCIONES",
  SET_LISTA_ACCIONES:"SET_LISTA_ACCIONES",
  }